model = "gpt-5.3-codex"
model_reasoning_effort = "low"

[features]
multi_agent = true

[projects."/Users/elvis/Documents/elviskahoro/attio-sdk-python"]
trust_level = "trusted"

[projects."/Users/elvis/Documents/elviskahoro/ai"]
trust_level = "trusted"

[projects."/Users/elvis/Documents/elviskahoro/oss-linter-trunk"]
trust_level = "trusted"

[projects."/Users/elvis"]
trust_level = "trusted"

[projects."/Users/elvis/Documents/elviskahoro/apollo-sdk-python"]
trust_level = "trusted"

[projects."/Users/elvis/Documents/elviskahoro/runtime-starter-pack"]
trust_level = "trusted"

[projects."/Users/elvis/Documents/elviskahoro/ai/tmp/dlt"]
trust_level = "trusted"

[projects."/Users/elvis/Documents/elviskahoro/ai/tmp/dlt-with-pipeline"]
trust_level = "trusted"

[projects."/Users/elvis/Documents/elviskahoro/dotfiles"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[mcp_servers]

[mcp_servers.dosu]
type = "http"
url = "https://api.dosu.dev/v1/mcp/deployments/d23fd603-faca-4166-8ba5-71414c8a9d81"

[mcp_servers.dosu.headers]
"X-Dosu-API-Key" = "${op://Personal/api-dosu/credential}"

[mcp_servers.fathom]
command = "npx"
args = ["-y", "mcp-remote", "https://api.fathom.ai/mcp"]

[mcp_servers.linear]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.linear.app/mcp"]

[mcp_servers.linear.env]
LINEAR_API_KEY = "${op://Personal/api-linear/credential}"

[mcp_servers.notion]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.notion.com/mcp"]

[mcp_servers.resend]
command = "npx"
args = ["-y", "resend-mcp"]

[mcp_servers.resend.env]
RESEND_API_KEY = "${op://Personal/api-resend/credential}"