# Environment & Setup
[ -f "$HOME/.env.local" ] && source "$HOME/.env.local"

# Load API keys from macOS Keychain for new shells.
# Add once with:
# security add-generic-password -U -a "$USER" -s OPENAI_API_KEY -w "sk-..."
# security add-generic-password -U -a "$USER" -s ANTHROPIC_API_KEY -w "sk-ant-..."
# security add-generic-password -U -a "$USER" -s WARP_API_KEY -w "oz_default_..."
if command -v security >/dev/null 2>&1; then
  OPENAI_API_KEY_VALUE="$(security find-generic-password -a "$USER" -s OPENAI_API_KEY -w 2>/dev/null)"
  [ -n "$OPENAI_API_KEY_VALUE" ] && export OPENAI_API_KEY="$OPENAI_API_KEY_VALUE"

  ANTHROPIC_API_KEY_VALUE="$(security find-generic-password -a "$USER" -s ANTHROPIC_API_KEY -w 2>/dev/null)"
  [ -n "$ANTHROPIC_API_KEY_VALUE" ] && export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY_VALUE"

  # WARP_API_KEY_VALUE="$(security find-generic-password -a "$USER" -s WARP_API_KEY -w 2>/dev/null)"
  # [ -n "$WARP_API_KEY_VALUE" ] && export WARP_API_KEY="$WARP_API_KEY_VALUE"
fi

# Functions
function cdl {
  cd "$(walk "$@")"
}

function cdf() {
  local path="${1/#\~/$HOME}"  # Expand ~ to $HOME
  cd "${path%/*}"
}

git_bcw() {
  local name="$1"
  git worktree add -b "$name" "../worktrees/$name" && cd "../worktrees/$name"
}

# Navigation - Directory shortcuts
alias ~='cd ~'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../../'
alias .6='cd ../../../../../../'

alias ai='cd /Users/elvis/Documents/elviskahoro/ai'
alias apollo='cd /Users/elvis/Documents/elviskahoro/ai/gtm/apollo'
alias attio='cd /Users/elvis/Documents/elviskahoro/ai/gtm/attio'
alias c='cdl'
alias cdc='cd ~/Documents/chalk'
alias cddocs='cd ~/Documents/'
alias cdcd='cd ~/Desktop'
alias cdd='cd ~/Desktop'
alias cdt='cd ~/Desktop/test/temp'
alias cddt='cd ~/Desktop/test/temp'
alias cdx='cd ~/Documents/chalk-ai'
alias cdobsidian='cd ~/Documents/obsidian'
alias cdshowcase='cd ~/Documents/showcase'
alias cdtrunk='cd ~/Documents/devx/.trunk/config'
alias cdwork='cd ~/Documents/workspace'
alias cdworkspace='cd ~/Documents/workspace'
alias cdv='cd ~/Documents/reflex-dev/devx'
alias cdr='cd ~/Documents/reflex-dev'
alias cx='cd ~/Documents/reflex-dev/devx'
alias dcx='cd ~/Documents/reflex-dev/devx'
alias ccdx='cd ~/Documents/reflex-dev/devx'
alias desk='cd ~/Desktop'
alias deks='cd ~/Desktop'
alias dsk='cd ~/Desktop'
alias docs='cd ~/Documents/'
alias dotfiles='cd /Users/elvis/Documents/elviskahoro/dotfiles'
alias down='cd ~/Downloads/'
alias dx='cd ~/Documents/reflex-dev/devx'
alias ekk='cd /Users/elvis/Documents/elviskahoro'
alias elvis='cd ~/Documents/elviskahoro'
alias fcdx='cd ~/Documents/reflex-dev/devx'
alias grow='cd /Users/elvis/Documents/elviskahoro/growth-machine'
alias growth='cd /Users/elvis/Documents/elviskahoro/growth-machine'
alias home='cd /Users/elvis/Documents/elviskahoro/obsidian'
alias play='cd ~/Documents/elviskahoro/playground'
alias cplay='play'
alias cplayh='play'
alias video='cd /Users/elvis/Downloads/videos'
alias vdx='cd ~/Documents/reflex-dev/devx'
alias writer='cd /Users/elvis/Documents/elviskahoro/writer'
alias zotero='cd ~/Documents/elviskahoro/zotero'

# Tools - Shortcuts & overrides
alias batp='bat --paging=never'
alias bl='black'
alias bbl='black'
alias vbl='black'
alias brwe='brew'
alias brw='brew'
alias cb='cargo build'
alias cla='claude --dangerously-skip-permissions --permission-mode bypassPermissions'
alias clx='codex --yolo'
alias cod='code'
alias cr='coderabbit'
alias cs='cursor'
alias cursor='cursor'
alias cursors='cursor'
alias dopller='doppler'
alias dui='duckdb --ui'
alias exa='eza'
alias fmt='trunk fmt'
alias jt='jupyter-lab'
alias less='less -R'
alias mo='marimo'
alias nfm='fnm'
alias ngroks='ngrok start warpdotdev'
alias o='open'
alias opne='open'
alias openm='open'
alias ope='open'
alias ping='ping -c 10'
alias pre='pre-commit run --all-files'
alias py='python'
alias pygithub='cd ~/Library/Caches/pypoetry/virtualenvs/warpdotdev-dx-_OAhpmWh-py3.10/lib/python3.10/site-packages/github'
alias refelx='reflex'
alias rr='reflex run'
alias rrld='reflex run --loglevel=debug'
alias sclaude='claude --dangerously-skip-permissions --permission-mode bypassPermissions'
alias slc='claude --dangerously-skip-permissions --permission-mode bypassPermissions'
alias scodex='codex --yolo'
alias senv='source .env.local'
alias slide='slides'
alias slid='slides'
alias sli='slides'
alias slx='codex --yolo'
alias tc='trunk check'
alias test='pytest -n auto -v'
alias tnew='tmux new -s'
alias tkill='tmux kill-session'
alias trukn='trunk'
alias trkn='trunk'
alias uvr='uv pip install -r requirements.txt'
alias vs='positron'
alias ws='positron'
alias warp='oz'
alias awrp='warp'

# File operations
alias cp='cp -i'
alias mkdir='mkdir -p'
alias mdir='mkdir -p'
alias mkldir='mkdir -p'
alias kmdir='mkdir -p'
alias mv='mv -i'
alias rmi='rm -iv'

# File listing & tree
alias le='ls'
alias ls='eza --absolute --oneline --git --group-directories-first --all --no-permissions --no-user --sort=Extension'
alias lst='eza --absolute --long --git --group-directories-first --all --modified --time-style=relative --no-permissions --no-user --sort=Extension'
alias lsc='eza | wc -l'
alias lsd='eza --absolute --oneline --git --all --no-permissions --no-user --sort=Extension -D'
alias lsl='lsd'
alias lks='lsd'
alias lsf='eza --absolute --oneline --git --all --no-permissions --no-user --sort=Extension -f'
alias tree='eza --tree --git-ignore'
alias treed='eza --tree --git-ignore --only-dirs'
alias rgf='rg -l'

# System utilities
alias diskspace="du -S | sort -n -r |more"
alias folders='du -h --max-depth=1'
alias folderssort='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
alias mountedinfo='df -hT'
alias powd='pwd'
alias ps='ps auxf'

# Permissions
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'
alias mx='chmod a+x'

# Python & development tools
alias pi='uv pip'
alias pipu='uv pip'
alias pipuv='uv pip'
alias piv='uv pip'
alias pipv='uv pip'
alias pyen='pyenv'
alias peynv='pyenv'
alias pyuenv='pyenv'
alias ve='source .venv/bin/activate'
alias vve='source .venv/bin/activate'
alias vce='source .venv/bin/activate'
alias verx='source /Users/elvis/Library/Caches/pypoetry/virtualenvs/reflex-NF09o5gF-py3.11/bin/activate'
alias whitelist='code /Users/elvis/Documents/reflex-dev/reflex-web/pcweb/whitelist.py'
alias white='code /Users/elvis/Documents/reflex-dev/reflex-web/pcweb/whitelist.py'

alias dparq='pqrs'
alias dcsv='xan'
alias djson='tw'
alias data='vd'

# Config editors (rc aliases)
alias rcb='vim ~/.bashrc'
alias rb='vim ~/.bashrc'
alias rcbp='vim ~/.bash_profile'
alias rcbs='source ~/.bashrc'
alias rcgb='vim ~/.bashrc'
alias rbc='vim ~/.bashrc'
alias rcg='vim ~/.gitconfig'
alias rcgf='vim ~/.gitconfig'
alias rcgm='vim ~/.config/git/.gitmessage'
alias rci='vim ~/.inputrc'
alias rcnvim='vim ~/.config/nvim/init.vim'
alias rcsh='vim ~/.ssh/config'
alias rcterm='vim ~/.config/alacritty/alacritty.yml'
alias rctig='vim ~/.tigrc'
alias rctmux='vim ~/.tmux.conf'
alias rcvim='vim ~/.vimrc'
alias rcp="vim ~/.profile"
alias rczp="vim ~/.zprofile"
alias rcze="vim ~/.zshenv"
alias rcz="vim ~/.zshrc"
alias zshrc="vim ~/.zshrc"
alias rczlogin="vim ~/.zlogin"
alias rczlogout="vim ~/.zlogout"
alias rcl="vim ~/.claude.json"
alias rcv='vim ~/.bashrc'
alias rvx='vim ~/.zshrc'

# Git
alias g='git'
alias ag='g'
alias au='g au'
alias brn='g brn'
alias bbc='g bucc'
alias buc='g bucc'
alias bucc='g bucc'
alias bnucc='g bucc'
alias bbu='g bu'
alias bu='g bu'
alias gbu='g bu'
alias ca='g ca'
alias cca='g cca'
alias cc='g cc'
alias gca='g ca'
alias gcca='g cca'
alias gbca='g bca'
alias gbc='g bc'
alias gbd='g bd'
alias qgbd='g bd'
alias gbcc='g bucc'
alias bcc='g bucc'
alias ucc='g bucc'
alias gbrd='g gbrd'
alias gch='g ch'
alias gcfa='g cfa'
alias cg='g'
alias co='g co'
alias gco='g co'
alias ct='g ct'
alias gct='g ct'
alias gtc='gt ct'
alias d='g d'
alias gd='g d'
alias dc='g dc'
alias dl='g dl'
alias gdl='g dl'
alias eg='g'
alias gls='g ls-files'
alias gl='g l'
alias gb='g'
alias G='g'
alias h='g'
alias q='g'
alias t='g'
alias gg='g'
alias ga='g'
alias gi='g'
alias gig='g'
alias qga='g'
alias yyg='g'
alias ggit='g'
alias gitg='g'
alias gaa='g aa'
alias gua='gau'
alias gau='g au'
alias grs='g rs'
alias greo='g reo'
alias reo='g reo'
alias gs='g s'
alias gst='g st'
alias gsta='g sta'
alias sta='g sta'
alias stp='g stp'
alias gspt='g stp'
alias stash='g stash'
alias gstd='g std'
alias gstp='g stp'
alias tp='g stp'
alias ggco='g gso'
alias gto='g to'
alias got='g to'
alias gtgo='g to'
alias gtopen='g to'
alias gtop='g top'
alias guso='g uso'
alias uso='g uso'
alias usr='g usr'
alias gusr='g usr'
alias suo='g uso'
alias pul='g pull'
alias pull='g pull'
alias psuh='g push'
alias push='g push'
alias gpush='g push'
alias poush='g push'
alias puush='g push'
alias pusrh='g push'
alias ush='g push'
alias wg='g'
alias yg='g'
alias tg='g'
alias jg='g'
alias lg='g'
alias qg='g'

